first_dbt_project_on_vm:
  outputs:
    dev:
      account: pe15223.southeast-asia.azure
      database: HDB
      password: 21J23e91.
      schema: public
      threads: 1
      type: snowflake
      user: alanzapex
      warehouse: COMPUTE_WH
  target: dev
